function plot_convergence(tt, JJ, x_phy, y_phy, z_phy)
    subplot(2,2,1)
            plot(tt, JJ)
            set(gca,'YScale','log')
            xlabel('\tau')
            ylabel('J(\tau)')
            title('Residual as a function of fictious time')
        subplot(2,2,2)
            plot(1:length(x_phy), x_phy)
            xlabel('t')
            ylabel('x(t)')
            title('x-coordinate as a function of time')
        subplot(2,2,3)
            plot(1:length(y_phy), y_phy)
            xlabel('t')
            ylabel('y(t)')
            title('y-coordinate as a function of time')
        subplot(2,2,4)
            plot(1:length(z_phy), z_phy)
            xlabel('t')
            ylabel('z(t)')
            title('z-coordinate as a function of time')    
end